/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUQuickControlProxHandOffSummaryViewUpdater : NSObject <HFProxControlActivityClientDelegate> {
    PCTelephonyActivity * _homePodPhoneCallActivity;
    NSObject<OS_dispatch_source> * _phoneCallStatusUpdateTimer;
    HUQuickControlSummaryNavigationBarTitleView * _titleView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) PCTelephonyActivity *homePodPhoneCallActivity;
@property (nonatomic, retain) NSObject<OS_dispatch_source> *phoneCallStatusUpdateTimer;
@property (readonly) Class superclass;
@property (nonatomic, retain) HUQuickControlSummaryNavigationBarTitleView *titleView;

- (void).cxx_destruct;
- (void)_invalidateHomePodPhoneCallStatusUpdateTimer;
- (bool)_isHomePodPhoneCallStatusUpdateTimerActive;
- (void)_startHomePodPhoneCallStatusUpdateTimer;
- (void)_updateSummaryViewForActivities:(id)arg1 disambiguationContext:(id)arg2;
- (void)dealloc;
- (void)didUpdateActivities:(id)arg1 forProxControlID:(id)arg2 disambiguationContext:(id)arg3;
- (id)homePodPhoneCallActivity;
- (id)initWithNavigationBarTitleView:(id)arg1;
- (id)phoneCallStatusUpdateTimer;
- (void)setHomePodPhoneCallActivity:(id)arg1;
- (void)setPhoneCallStatusUpdateTimer:(id)arg1;
- (void)setTitleView:(id)arg1;
- (id)titleView;

@end
