/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFSingleStepHomeScreenShortcutCompletionDialogViewController : WFCompactDialogViewController

- (void)loadView;
- (void)viewDidAppear:(bool)arg1;

@end
