/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI
 */

@interface WFSetWallpaperActionUIKitUserInterface : WFActionUserInterface <SBSUIWallpaperPreviewViewControllerDelegate, WFSetWallpaperActionUserInterface> {
    id /* block */  _completionHandler;
    NSDictionary * _images;
    long long  _locations;
    NSDictionary * _options;
}

@property (nonatomic, copy) id /* block */ completionHandler;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSDictionary *images;
@property (nonatomic) long long locations;
@property (nonatomic, retain) NSDictionary *options;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)cancelPresentationWithCompletionHandler:(id /* block */)arg1;
- (id /* block */)completionHandler;
- (void)finishWithError:(id)arg1;
- (id)images;
- (long long)locations;
- (id)options;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)setImages:(id)arg1;
- (void)setLocations:(long long)arg1;
- (void)setOptions:(id)arg1;
- (void)showPreviewWithInput:(id)arg1 key:(id)arg2 wallpaperLocation:(long long)arg3 completionHandler:(id /* block */)arg4;
- (void)wallpaperPreviewViewControllerCancelButtonPressed:(id)arg1;
- (void)wallpaperPreviewViewControllerSetButtonPressed:(id)arg1;

@end
